# .readthedocs.yaml
# Configuration for building documentation on Read the Docs
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build with the latest Ubuntu environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Configure the Django environment for Sphinx's autodoc
      - echo "export DJANGO_SETTINGS_MODULE=docs_settings" >> $BASH_ENV

# Use Sphinx as the documentation builder
sphinx:
  configuration: docs/conf.py
  # fail_on_warning: true # Uncomment for strict quality control

# Define how to install the Python environment
python:
  install:
    - method: pip
      path: .  # Install the package from the root directory
      extra_requirements:
        - docs  # This installs the 'docs' extra_requires from setup.py/pyproject.toml
  system_packages: false # We don't need OS-level packages for a pure Python project

# Optionally build these formats (PDF is often skipped for code projects)
formats:
  - htmlzip
  # - pdf

# Optionally, you can include a hook to run any custom commands
# commands:
#   pre_build:
#     - some-custom-command