# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]

# Use setup commands instead of environment modification
setup:
  - echo "Setting up Django environment"
  - export DJANGO_SETTINGS_MODULE=docs_settings