# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]

# Use environment variables instead of trying to modify BASH_ENV
environment:
  DJANGO_SETTINGS_MODULE: docs_settings

# Alternative approach using setup commands
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]

# Set environment variables directly
environment:
  DJANGO_SETTINGS_MODULE: "docs_settings"