# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]

# Set the environment variable directly
environment:
  DJANGO_SETTINGS_MODULE: "docs_settings"