# Configuration for building documentation on Read the Docs
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  # Jobs must be under the specific os configuration
  jobs:
    post_create_environment:
      # Configure the Django environment for Sphinx's autodoc
      - echo "export DJANGO_SETTINGS_MODULE=docs_settings" >> $BASH_ENV

# Use Sphinx as the documentation builder
sphinx:
  configuration: docs/conf.py
  # fail_on_warning: true # Uncomment for strict quality control

# Define how to install the Python environment
python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]  # Fixed syntax - use list format

# Optionally build these formats
formats:
  - htmlzip
  # - pdf