# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
import django
from datetime import datetime


# Add the project root to the Python path
sys.path.insert(0, os.path.abspath('..'))

# Set Django settings module for Read the Docs environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'docs_settings')

try:
    django.setup()
    print("Django setup successful!")
except Exception as e:
    print(f"Warning: Django setup failed: {e}")
    print("This may affect autodoc functionality for Django models")
    # Continue anyway - some documentation will still work

# ... rest of your conf.py configuration
# -- Path Setup --------------------------------------------------------------
# Add the project root directory to the Python path so Sphinx can find the 'referral' app.

# -- Django Setup ------------------------------------------------------------
# This is critical for `autodoc` to successfully import Django models and utilities.
# os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'docs_settings')
# django.setup()

# -- Project Information -----------------------------------------------------
project = 'Django Referral'
copyright = f'{datetime.now().year}, Andrew Oduola'
author = 'Andrew Oduola'

# The short X.Y version (e.g., 0.1)
version = '0.1'
# The full version, including alpha/beta/rc tags (e.g., 0.1.0)
release = '0.1.0'

# -- General Configuration ---------------------------------------------------
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',       # Automatically generate docs from docstrings
    'sphinx.ext.viewcode',      # Add links to highlighted source code
    'sphinx.ext.napoleon',      # Support for Google-style docstrings (much cleaner)
    'sphinx.ext.intersphinx',   # Link to other projects' documentation (e.g., Django)
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML Output -------------------------------------------------
# The theme to use for HTML and HTML Help pages. See the documentation for
# a list of builtin themes.
html_theme = 'furo'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# -- Extension configuration -------------------------------------------------
# Napoleon (Google docstring) settings
napoleon_google_docstring = True
napoleon_include_init_with_doc = True

# Intersphinx mapping: allows linking to external docs (e.g., Django, Python)
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'django': ('https://docs.djangoproject.com/en/stable/', 'https://docs.djangoproject.com/en/stable/_objects/'),
}